## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

c:\Users\achsr\anaconda31\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


EIN                                      NAME APPLICATION_TYPE   
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB              T10  \
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR               T3   
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS               T5   
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION               T3   
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT               T3   

        AFFILIATION CLASSIFICATION      USE_CASE  ORGANIZATION  STATUS   
0       Independent          C1000    ProductDev   Association       1  \
1       Independent          C2000  Preservation  Co-operative       1   
2  CompanySponsored          C3000    ProductDev   Association       1   
3  CompanySponsored          C2000  Preservation         Trust       1   
4       Independent          C1000     Heathcare         Trust       1   

      INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0              0                      N     5000              1  
1         1-9999                      N   108590              1  
2              0                      N     5000              0  
3    10000-24999                      N     6692              1  
4  100000-499999                      N   142590              1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
app_df_clean = application_df.drop(columns=['EIN', 'NAME'])
app_df_clean.head(2)

APPLICATION_TYPE  AFFILIATION CLASSIFICATION      USE_CASE  ORGANIZATION   
0              T10  Independent          C1000    ProductDev   Association  \
1               T3  Independent          C2000  Preservation  Co-operative   

   STATUS INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0       1          0                      N     5000              1  
1       1     1-9999                      N   108590              1

In [3]:
# Determine the number of unique values in each column.
app_df_clean.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = app_df_clean['APPLICATION_TYPE'].value_counts()
app_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_counts[app_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
class_counts = app_df_clean['CLASSIFICATION'].value_counts()
class_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...  
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts[class_counts > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
#assuming cutoff 1000
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
app_df_clean = pd.get_dummies(app_df_clean)
app_df_clean.head()

STATUS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_T10  APPLICATION_TYPE_T12   
0       1     5000              1                  True                 False  \
1       1   108590              1                 False                 False   
2       1     5000              0                 False                 False   
3       1     6692              1                 False                 False   
4       1   142590              1                 False                 False   

   APPLICATION_TYPE_T13  APPLICATION_TYPE_T14  APPLICATION_TYPE_T15   
0                 False                 False                 False  \
1                 False                 False                 False   
2                 False                 False                 False   
3                 False                 False                 False   
4                 False                 False                 False   

   APPLICATION_TYPE_T17  APPLICATION_TYPE_T19  ...  INCOME_AMT_1-9999   
0                 False                 False  ...              False  \
1                 False                 False  ...               True   
2                 False                 False  ...              False   
3                 False                 False  ...              False   
4                 False                 False  ...              False   

   INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  INCOME_AMT_10M-50M   
0                   False                     False               False  \
1                   False                     False               False   
2                   False                     False               False   
3                    True                     False               False   
4                   False                      True               False   

   INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  INCOME_AMT_50M+   
0             False                   False            False  \
1             False                   False            False   
2             False                   False            False   
3             False                   False            False   
4             False                   False            False   

   INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y  
0              False                      True                     False  
1              False                      True                     False  
2              False                      True                     False  
3              False                      True                     False  
4              False                      True                     False  

[5 rows x 117 columns]

In [10]:
# Split our preprocessed data into our features and target arrays
x = app_df_clean.drop(columns=['IS_SUCCESSFUL']).values
y = app_df_clean['IS_SUCCESSFUL'].values



In [11]:
x[0]

array([1, 5000, True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, True, False, False, False, False, True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, True, True,
       False, False, False, True, False, False, False, False, False,
       False, False, False, True, False], dtype=object)

In [12]:
y

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [13]:
# Split the preprocessed data into a training and testing dataset
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [14]:
x_train[0]

array([1, 4564513, False, False, False, False, False, False, False, False,
       False, False, False, False, True, False, False, False, False, True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, True, True,
       False, False, False, False, False, False, False, False, True,
       False, False, False, True, False], dtype=object)

In [15]:
x_test[0]

array([1, 5000, False, False, False, False, False, False, False, False,
       False, False, True, False, False, False, False, False, False,
       False, False, True, False, False, False, False, True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, True, False,
       False, False, False, True, True, False, False, False, False, False,
       False, False, False, True, False], dtype=object)

In [16]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
x_scaler = scaler.fit(x_train)

# Scale the data
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled = x_scaler.transform(x_test)
print(x_train_scaled[0])

[ 0.01079982  0.01406104 -0.12375046 -0.02925687 -0.04368605 -0.01079982
 -0.00881785 -0.00623504 -0.1781152  -0.01870803 -0.00623504 -0.00623504
 -1.9350387  -0.21484611  5.31336223 -0.19518001 -0.14808487 -0.14698452
 -0.06247072  1.08798033 -0.04413044 -1.08051343 -0.03118975 -0.01079982
 -0.01972038 -0.01079982 -1.00827557 -0.40325441 -0.03473549 -0.00881785
 -0.01649829  0.         -0.01527415 -0.01763775 -0.02991499  0.
 -0.00623504 -0.00623504 -0.02160343 -0.00623504 -0.01079982 -0.01079982
 -0.00623504 -0.06023636 -0.01870803 -0.03946378  0.         -0.04043991
 -0.00623504 -0.033595   -0.02068331  0.         -0.00623504 -0.00881785
 -0.0935134  -0.01247081 -0.00623504 -0.00623504 -0.02068331  0.
  0.         -0.46720535 -0.23900151 -0.00623504  0.         -0.00623504
 -0.0324146   0.         -0.00881785 -0.00623504  0.         -0.00623504
 -0.00623504 -0.05654979 -0.01079982 -0.05148254  4.12939824 -0.00881785
 -0.00623504 -0.07735206 -0.01079982 -0.00623504 -0.00623504 -0.006

## Compile, Train and Evaluate the Model

In [22]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num_input_features = len(x_train[0])
layer_1_nodes = 80
layer_2_nodes = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer_1_nodes,
            input_dim=num_input_features,
            activation='relu')
)

# Second hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer_2_nodes,
            input_dim=layer_1_nodes,
            activation='relu')
)

# Output layer
nn.add(
    tf.keras.layers.Dense(units=1,
        input_dim=layer_2_nodes,
        activation='sigmoid')
)

# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 80)                9360      
                                                                 
 dense_8 (Dense)             (None, 30)                2430      
                                                                 
 dense_9 (Dense)             (None, 1)                 31        
                                                                 
Total params: 11821 (46.18 KB)
Trainable params: 11821 (46.18 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [27]:
# Train the model
fit_model = nn.fit(x_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.5739 - accuracy: 0.7233
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5531 - accuracy: 0.7292
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7317
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7338
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5446 - accuracy: 0.7347
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7353
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7354
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7355
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7350
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accura

In [29]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(x_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5648 - accuracy: 0.7297 - 310ms/epoch - 1ms/step
Loss: 0.5648002028465271, Accuracy: 0.72967928647995


In [30]:
# Export our model to HDF5 file
nn.save('alphabet_soup.h5')

c:\Users\achsr\anaconda31\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
